# Loss Tests

### MSE Loss

In [1]:
import torch
from loss import MSELoss
torch.manual_seed(0)

torch_loss = torch.nn.MSELoss()
my_loss = MSELoss()

# PyTorch MSELoss
input = torch.randn(3, 5, dtype = torch.float32, requires_grad=True)
target = torch.randn(3, 5, dtype = torch.float32)
output_torch = torch_loss(input, target)
output_torch.backward()
print(output_torch)
print(input.grad)

# My MSELoss
input = input.detach().numpy()
target = target.detach().numpy()
output_my = my_loss(input, target)
print(output_my)
print(my_loss.backward())

tensor(1.6508, grad_fn=<MseLossBackward0>)
tensor([[ 0.1891,  0.0364, -0.3403,  0.1947,  0.0566],
        [-0.2359, -0.1404, -0.0136, -0.1992, -0.0794],
        [-0.2481,  0.1963, -0.0087,  0.1495, -0.0470]])
1.6508407592773438
[[ 0.18910597  0.03638515 -0.34025386  0.19472355  0.05661138]
 [-0.23586519 -0.14042075 -0.01357114 -0.19921419 -0.07936172]
 [-0.24805735  0.19632955 -0.00874292  0.14953116 -0.04702764]]


### Binary Cross Entropy Loss

In [1]:
import torch
from loss import BCELoss
torch.manual_seed(0)

torch_loss = torch.nn.BCELoss()
my_loss = BCELoss()

# PyTorch BCELoss
input = torch.rand(size = (5,), dtype = torch.float32, requires_grad = True)
target = torch.randint(low = 0, high = 1, size = (5,), dtype = torch.float32)
output_torch = torch_loss(input, target)
output_torch.backward()
print(output_torch)
print(input.grad)

# My BCELoss
input = input.detach().numpy()
target = target.detach().numpy()
output_my = my_loss(input, target)
print(output_my)
print(my_loss.backward())

tensor(0.5498, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([0.3970, 0.8629, 0.2194, 0.2304, 0.2888])
0.5498471736907959
[0.39702752 0.8628939  0.21941312 0.23042282 0.28877646]


# Layer Tests

## Linear

In [1]:
import torch
from layers.linear import Linear
torch.manual_seed(0)

torch_linear = torch.nn.Linear(20, 30)
my_linear = Linear(20, 30)

# PyTorch Linear
input = torch.randn(128, 20, dtype = torch.float32, requires_grad=True)
output = torch_linear(input)
print(output.shape)

# My Linear
input = input.detach().numpy()
output = my_linear(input)
print(output.shape)

torch.Size([128, 30])
(128, 30)
