# Linear Regression

### sklearn

In [1]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error

# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)
diabetes_y = diabetes_y[:, np.newaxis]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X, diabetes_y)

# Make predictions
diabetes_y_pred = regr.predict(diabetes_X)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y, diabetes_y_pred))

Coefficients: 
 [[ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
   476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]]
Mean squared error: 2859.70


### My Linear Regression

In [2]:
from regression import LinearRegression

myLinearRegression = LinearRegression(lr = 0.1, n_iter = 100)
myLinearRegression.train(diabetes_X, diabetes_y)

# Make predictions
diabetes_y_pred = myLinearRegression.forward(diabetes_X)

# The coefficients
print("Coefficients: (with intercept) \n", myLinearRegression.linear.W.T)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y, diabetes_y_pred))

Coefficients: (with intercept) 
 [[152.13348413  12.33992707   2.17218538  40.2267391   30.3267757
   13.32843937  10.66878865 -27.04883347  28.48791097  38.85309245
   25.83861555]]
Mean squared error: 5259.18


In [3]:
myLinearRegression = LinearRegression(lr = 0.1, momentum = 0.9, n_iter = 100)
myLinearRegression.train(diabetes_X, diabetes_y)

# Make predictions
diabetes_y_pred = myLinearRegression.forward(diabetes_X)

# The coefficients
print("Coefficients: (with intercept) \n", myLinearRegression.linear.W.T)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y, diabetes_y_pred))

Coefficients: (with intercept) 
 [[ 152.56810579   52.66413023  -25.02680574  256.92545182  181.43605452
    43.32743061   19.36909085 -150.98649408  140.16635347  230.13899368
   133.85527942]]
Mean squared error: 3415.96


# Logistic Regression

### sklearn

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

X, y = load_iris(return_X_y=True)
# get first 100 samples, for only two classes
X = X[:100]
y = y[:100, np.newaxis]

clf = LogisticRegression(penalty = None).fit(X, y)

# Make predictions
y_proba = clf.predict_proba(X)

# The coefficients
print("Coefficients:\n", clf.coef_)
# The Accuracy
print("Log Loss: %.8f" % log_loss(y, y_proba))

Coefficients:
 [[-2.07247339 -6.90694692 10.97006745  5.64543091]]
Log Loss: 0.00000087


/Users/xiaoyubi/Desktop/Study/My-ML-Base/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### My Logistic Regression

In [3]:
from regression import LogisticRegression

myLogisticRegression = LogisticRegression(lr = 0.1, n_iter = 100)
myLogisticRegression.train(X, y)

# Make predictions
y_proba = myLogisticRegression.forward(X)

# The coefficients
print("Coefficients: (with intercept)\n", myLogisticRegression.linear.W.T)
# The Accuracy
print("Log Loss: %.8f" % log_loss(y, y_proba))

Coefficients: (with intercept)
 [[-0.16040407 -0.21811472 -1.08592809  1.4777955   0.82001462]]
Log Loss: 0.07017529


In [4]:
from regression import LogisticRegression

myLogisticRegression = LogisticRegression(lr = 0.1, momentum = 0.9, n_iter = 100)
myLogisticRegression.train(X, y)

# Make predictions
y_proba = myLogisticRegression.forward(X)

# The coefficients
print("Coefficients: (with intercept)\n", myLogisticRegression.linear.W.T)
# The Accuracy
print("Log Loss: %.8f" % log_loss(y, y_proba))

Coefficients: (with intercept)
 [[-0.42276576 -0.8043667  -2.32423192  3.85622503  1.75378522]]
Log Loss: 0.00285581
